# Generated by Django 4.0.1 on 2022-01-18 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='inquilino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_inquilino', models.CharField(max_length=200)),
                ('idade_inquilino', models.IntegerField()),
                ('email_inquilino', models.EmailField(max_length=254)),
                ('telefone_inquilino', models.IntegerField()),
                ('sexo_inquilino', models.CharField(max_length=100)),
            ],
        ),
    ]
