# Generated by Django 4.0.1 on 2022-01-20 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DespesaUnidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_despesa_unidade', models.CharField(max_length=400)),
                ('tipo_despesa_unidade', models.CharField(max_length=200)),
                ('vencimento_fatura_unidade', models.CharField(max_length=100)),
                ('status_pagamento_unidade', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Inquilinos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_inquilino', models.CharField(max_length=200)),
                ('idade_inquilino', models.IntegerField()),
                ('email_inquilino', models.EmailField(max_length=254)),
                ('telefone_inquilino', models.IntegerField()),
                ('sexo_inquilino', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Unidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_unidade', models.IntegerField()),
                ('condominio_unidade', models.CharField(max_length=200)),
                ('endereco_unidade', models.CharField(max_length=200)),
                ('proprietario_unidade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inquilinos.inquilinos')),
            ],
        ),
        migrations.AddField(
            model_name='inquilinos',
            name='unidade_inquilino',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inquilinos.unidades'),
        ),
    ]
